const SHA256 = require('crypto-js/sha256');

class Block{
    //Creates an object in the Block class. You will need the index (which block is it), timestamp (when the block is created), the data included in the block, and the hash of the previous block. The hash for this block is autogenerated with the creation of the block.
    constructor( index, timestamp, data, previousHash="" ){
        this.index = index;
        this.timestamp = timestamp;
        this.data = data;
        this.previousHash = previousHash;
        this.hash = calculateHash();
    }

    //This functions calculates the hash of the current Block.
    calculateHash(){
        return SHA256(this.index + this.previousHash + this.timestamp + JSON.stringify(this.data)).toString();
    }

}

class Blockchain{
    //This creates a Blockchain with an array as an attribute
    constructor(){
        this.chain=[];
    }

    //This creates the base block or the first block in the blockchain
    createGenesisBlock(){
        let genesis =  new Block(0, "03/01/2009", "Genesis Block", "0");
        this.chain.push(genesis);
        return genesis;
    }

    //This adds a block into the blockchain using the data given. The index will be the # of the block created, date will be the date created, data will be a string inputed by user, and previous has will be the hash of the block before it.
    addBlock( data ){
        try {
            let toAdd = new Block(this.chain.length, String(new Date().toLocaleString().split(",")[0]) , String(data), String(this.chain[this.chain.length-1].hash));
            this.chain.push(toAdd);
            return toAdd;
        }
        catch(err){
            return ("Unsuccessful");
        }
    }

}

//This creates a new Blockchain object
let chain = new Blockchain();
//This creates the first block in the blockchain
chain.createGenesisBlock();
//This adds a block in the blockchain with the data being "Hello"
chain.addBlock("Hello");